### ISSUE TITLE
DDS-Record-Replay supports `info` and `list` command to peek the mcap file?

### ISSUE THREAD

**Issue by fujitatomoya** [eProsima/DDS-Record-Replay#109]
### Description / Questions

- https://dds-recorder.readthedocs.io/en/latest/rst/recording/usage/configuration.html
- https://dds-recorder.readthedocs.io/en/latest/rst/replaying/usage/configuration.html

provides many configuration for record and replay, most likely related to DDS configuration.

on the other hand, doc does not say anything about the command line interface to check the recorded data file to peek, e.g `ros2 bag info` or `ros2 bag list`.
those features are really user-friendly after recording and before playing to see what is stored in the recorded data.

if `mcap CLI` is supposed to be used in these use cases since it uses `mcap` underneath data format, i believe that it should be explained in user manual as well, including `mcap CLI` installation. (https://mcap.dev/guides/cli)

**Comment by juanlofer-eprosima** [comment]
Hi @fujitatomoya , the features you mention are indeed quite useful for users, but you are right, we did not implement them since `mcap CLI` already offers this functionality and that's in fact the tool we use for this purpose. We will be taking your suggestion into account and inform the user about this possibility in a future PR.

**Comment by juanlofer-eprosima** [comment]
Addressed in #111
